### PR TITLE
APP-6037 Fix destroyed browser windows

### PR DESCRIPTION
**Pull request by blakelee-pendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-designer-electron/26)

### CODE REVIEW

**Comment by 4storia** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/26#-:-L2VoF0KIm25tk8NNh9M:bnfp4nl)*

**Comment by 4storia** [comment]
[merge]

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/26#-:-L2VoGW1b_D-_G1GNUB-:b3sq3yz)*

**Comment by 4storia** [comment]
[merge]

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/26#-:-L2VoMvTqKIevjgd8Hju:b3sq3yz)*

**Comment by pendo-ops** [comment]
All JIRA issue transitions failed.
* [APP-6037](https://pendo-io.atlassian.net/browse/APP-6037): Jira Issue APP-6037: Not changed to Master


Failed to delete branch brl-APP-6037-fix-destroyed-browser-windows

**Pull request merged**
