### PR TITLE
APP-6230 multi window support

### PR DESCRIPTION
**Pull request by blakelee-pendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-designer-electron/28)

### CODE REVIEW

**Comment by 4storia** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[contentScript.js, line 10 at r1](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28#-L3ZW6HKEdnYP-BY9La3:-L3ZW6HKEdnYP-BY9La4:bup7568) ([raw file](https://github.com/pendo-io/pendo-designer-electron/blob/a87ef6cfa6170e8bbed5bd8b7fc4e0559e8f123d/contentScript.js#L10)):*
> ```JavaScript
> const MESSAGE_SOURCE_CONTENT_SCRIPT = 'pendo-designer-content-script';
> 
> let windowPairings = {};
> ```

this can be const right?

---

*[contentScript.js, line 14 at r1](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28#-L3ZW8JG_W_LDUn8vaCl:-L3ZW8JG_W_LDUn8vaCm:b-6ksccl) ([raw file](https://github.com/pendo-io/pendo-designer-electron/blob/a87ef6cfa6170e8bbed5bd8b7fc4e0559e8f123d/contentScript.js#L14)):*
> ```JavaScript
> 
> function addLaunchDesignerFnsToWindow(event) {
> 	event.sender.executeJavaScript(`
> ```

wtf are these tabs. get these tabs outta here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28#-:-L3ZWg_C0CcfRmELbCu-:bnfp4nl)*

**Comment by blakelee-pendo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[contentScript.js, line 10 at r1](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28#-L3ZW6HKEdnYP-BY9La3:-L3ZY9zhgsZOQk3Qqksc:b-896fix) ([raw file](https://github.com/pendo-io/pendo-designer-electron/blob/a87ef6cfa6170e8bbed5bd8b7fc4e0559e8f123d/contentScript.js#L10)):*
<details><summary><i>Previously, 4storia (Cliff Hess) wrote…</i></summary><blockquote>

this can be const right?
</blockquote></details>

Done.

---

*[contentScript.js, line 14 at r1](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28#-L3ZW8JG_W_LDUn8vaCl:-L3ZY9nDVtBS5Tj1RwTh:b-896fix) ([raw file](https://github.com/pendo-io/pendo-designer-electron/blob/a87ef6cfa6170e8bbed5bd8b7fc4e0559e8f123d/contentScript.js#L14)):*
<details><summary><i>Previously, 4storia (Cliff Hess) wrote…</i></summary><blockquote>

wtf are these tabs. get these tabs outta here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28)*

**Comment by ashuser-pendo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28#-:-L3ZZFIRLhg_sTKtLY_a:bnfp4nl)*

**Comment by jordanakerr** [comment]
*[contentScript.js, line 211 at r2](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28#-L3ZbEFYfPcafe17Yrd2:-L3ZbEFZmDYwbzDM4zHy:b-96zirg) ([raw file](https://github.com/pendo-io/pendo-designer-electron/blob/4905ae6e59e4e9c724bea4cf88d3ea2237746324/contentScript.js#L211)):*
> ```JavaScript
>     };
> ```

lots of spaces!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28)*

**Comment by 4storia** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28)*

**Comment by blakelee-pendo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[contentScript.js, line 211 at r2](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28#-L3ZbEFYfPcafe17Yrd2:-L3ZjiG5gcGnKzs97HCA:beewjic) ([raw file](https://github.com/pendo-io/pendo-designer-electron/blob/4905ae6e59e4e9c724bea4cf88d3ea2237746324/contentScript.js#L211)):*
<details><summary><i>Previously, jordanakerr (Jordana Kerr) wrote…</i></summary><blockquote>

lots of spaces!
</blockquote></details>

line breaks?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28)*

**Comment by jordanakerr** [comment]
*[contentScript.js, line 211 at r2](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28#-L3ZbEFYfPcafe17Yrd2:-L3ZkF-9j3_ojCEPUciY:b-e506gx) ([raw file](https://github.com/pendo-io/pendo-designer-electron/blob/4905ae6e59e4e9c724bea4cf88d3ea2237746324/contentScript.js#L211)):*
<details><summary><i>Previously, blakelee-pendo (Blake Lee) wrote…</i></summary><blockquote>

line breaks?
</blockquote></details>

yes. unblocking though, just being annoying

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28)*

**Comment by blakelee-pendo** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[contentScript.js, line 211 at r2](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28#-L3ZbEFYfPcafe17Yrd2:-L3ZkIrbUvL-ELJZjC2M:b-abqlmx) ([raw file](https://github.com/pendo-io/pendo-designer-electron/blob/4905ae6e59e4e9c724bea4cf88d3ea2237746324/contentScript.js#L211)):*
<details><summary><i>Previously, jordanakerr (Jordana Kerr) wrote…</i></summary><blockquote>

yes. unblocking though, just being annoying
</blockquote></details>

np, I can fix it, was curious if it was line breaks or space at the beginning of the lines

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28)*

**Comment by blakelee-pendo** [comment]
Do not merge yet

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28#-:-L3ZkQUv1bVnNYcfxKMO:b-cfwyil)*

**Comment by 4storia** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28)*

**Comment by 4storia** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28)*

**Comment by blakelee-pendo** [comment]
ready for merge

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28#-:-L3cZny6-3J5N4WUoG9L:b-lf783l)*

**Comment by blakelee-pendo** [comment]
+@cminowicz 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28#-:-L3cZpvQ4fQXd6DhANPK:b-qm1x5b)*

**Comment by cminowicz** [comment]
:lgtm: Verified on app, reviewed code, and updated QE docs on confluence. A++. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28#-:-L3dLMfYYfrbrl-wnnO0:bxi9tng)*

**Comment by 4storia** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28)*

**Comment by 4storia** [comment]
[merge]

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/pendo-designer-electron/28#-:-L3dLjuPzWNTbPNC-NqO:b3sq3yz)*

**Comment by pendo-ops** [comment]
All JIRA issue transitioned to new values.
* [APP-6230](https://pendo-io.atlassian.net/browse/APP-6230): Jira Issue APP-6230: Changed to Master


Failed to delete branch APP-6230-multi-window-support

**Pull request merged**
